### ISSUE TITLE
Any planned releases for a Raspberry Pi OS?

### ISSUE THREAD

**Issue by c0defire** [curusarn/resh#69]
I have a Raspberry Pi 3 b+ and whole love this tool to work on ARM CPUs.

**Comment by curusarn** [comment]
I have just added arm and arm64 architectures to the build process and install script for you.

Everything should work on RPi now. Let me know if something doesn't.

**Comment by polipones** [comment]
I have problem with installing on RPi4. See screenshot for more info.
![image](https://user-images.githubusercontent.com/61013387/84545969-920aad80-ad00-11ea-822e-a783c7a0f4dd.png)

**Comment by curusarn** [comment]
Should be fixed by: https://github.com/curusarn/resh/commit/73ca6c27f1b45af29d64da732074969415b12b5d

@polipones: Can you test it please?

**Comment by polipones** [comment]
Hi, I tested it and it still doesn't work. It seems to have problem with binary execution.
![image](https://user-images.githubusercontent.com/61013387/85173931-a0af1280-b274-11ea-9d2c-dcd363bd9b6b.png)

Here is uname -a output: Linux nas.local 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

**Comment by curusarn** [comment]
@polipones: Oh, armv71 is 32bit - my bad. Try now.

**Comment by polipones** [comment]
Nope, bad news :smile:. Is there any log, that I can send to you?
![image](https://user-images.githubusercontent.com/61013387/85175592-1072cc80-b278-11ea-8a13-10177fb317bc.png)

**Comment by polipones** [comment]
Oh hey, I just noticed that it was trying again to run 64bit version (I was running it from cloned git repo). So I ran the simple one command installation and it worked. Thx for help.

**Comment by curusarn** [comment]
Happy to help.
